version: "3"
services:
  apachephp:
    build:
      context: ./../
      dockerfile: ./docker/containers/apache-php/dev/Dockerfile
    environment:
      APP_ENV: "dev"
    volumes:
    - ../src:/var/www/html
